FROM node:16-alpine

WORKDIR /usr/app/

# copy the config files
COPY ./package.json ./
COPY ./tsconfig.json ./
COPY ./next.config.js ./
COPY ./next-env.d.ts ./

# install dependencies
RUN yarn install

# copy the source code
COPY ./ ./

CMD ["yarn", "dev"]