version: "3"

services:
  selenium-firefox:
    container_name: selenium-firefox
    image: selenium/standalone-firefox:latest
    restart: always
    ports:
      - ${SELENIUM_HOST_PORT}:${SELENIUM_CONTAINER_PORT}

  postgres:
    container_name: digiqore-scraper-postgres
    image: postgres:14
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5431:5432

  digiqore-scraper-backend:
    container_name: digiqore-scraper-backend
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    ports:
      - 3001:3000
    depends_on:
      - postgres
      - selenium-firefox

  digiqore-scraper-frontend:
    container_name: digiqore-scraper-frontend
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    ports:
      - 3002:3000
    depends_on:
      - postgres
      - selenium-firefox
      - digiqore-scraper-backend