FROM node:16-alpine

WORKDIR /usr/app/

RUN apk add firefox

# copy the config files
COPY ./package.json ./
COPY ./tsconfig.json ./

# install dependencies
RUN yarn install

# copy the source code
COPY ./ ./

ENTRYPOINT ["/bin/sh", "./entrypoint.dev.sh"]